package test.integration.auth;

import com.bazaarvoice.emodb.auth.apikey.ApiKey;
import com.bazaarvoice.emodb.auth.apikey.ApiKeyRealm;
import com.bazaarvoice.emodb.auth.apikey.ApiKeyRequest;
import com.bazaarvoice.emodb.auth.apikey.ApiKeySecurityManager;
import com.bazaarvoice.emodb.auth.identity.InMemoryAuthIdentityManager;
import com.bazaarvoice.emodb.auth.permissions.InMemoryPermissionManager;
import com.bazaarvoice.emodb.auth.permissions.PermissionUpdateRequest;
import com.bazaarvoice.emodb.auth.role.InMemoryRoleManager;
import com.bazaarvoice.emodb.auth.role.RoleIdentifier;
import com.bazaarvoice.emodb.auth.role.RoleUpdateRequest;
import com.bazaarvoice.emodb.blob.api.BlobStore;
import com.bazaarvoice.emodb.common.dropwizard.task.TaskRegistry;
import com.bazaarvoice.emodb.sor.api.DataStore;
import com.bazaarvoice.emodb.web.auth.ApiKeyAdminTask;
import com.bazaarvoice.emodb.web.auth.EmoPermissionResolver;
import com.bazaarvoice.emodb.web.auth.Permissions;
import com.bazaarvoice.emodb.web.auth.resource.NamedResource;
import com.google.common.collect.ImmutableMultimap;
import com.google.common.collect.ImmutableSet;
import com.google.common.net.HostAndPort;
import org.apache.shiro.cache.MemoryConstrainedCacheManager;
import org.apache.shiro.util.ThreadContext;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.stream.Collectors;

import static org.mockito.Mockito.mock;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertNull;

public class ApiKeyAdminTaskTest {

    private ApiKeyAdminTask _task;
    private InMemoryAuthIdentityManager<ApiKey> _authIdentityManager;
    private InMemoryRoleManager _roleManager;

    @BeforeMethod
    public void setUp() {
        _authIdentityManager = new InMemoryAuthIdentityManager<>();
        EmoPermissionResolver permissionResolver = new EmoPermissionResolver(mock(DataStore.class), mock(BlobStore.class));
        InMemoryPermissionManager permissionManager = new InMemoryPermissionManager(permissionResolver);
        _roleManager = new InMemoryRoleManager(permissionManager);

        ApiKeySecurityManager securityManager = new ApiKeySecurityManager(
                new ApiKeyRealm("test", new MemoryConstrainedCacheManager(), _authIdentityManager, permissionManager,
                        null));

        _task = new ApiKeyAdminTask(securityManager, mock(TaskRegistry.class), _authIdentityManager,
                HostAndPort.fromParts("0.0.0.0", 8080), ImmutableSet.of("reservedrole"));

        createApiKeyWithPermissions("test-admin", Permissions.unlimitedApiKey(), Permissions.unlimitedRole());
    }

    private void createApiKeyWithPermissions(String key, String... permissions) {
        String role = key + "-role";
        String internalId = key + "-id";

        _roleManager.createRole(new RoleIdentifier(null, role),
                new RoleUpdateRequest().withPermissionUpdate(new PermissionUpdateRequest().permit(
                        ImmutableSet.copyOf(permissions))));

        _authIdentityManager.updateIdentity(new ApiKey(key, internalId, ImmutableSet.of(role)));
    }

    @AfterMethod
    public void tearDown() {
        ThreadContext.remove();
    }

    @Test
    public void testCreateNewApiKey() throws Exception {
        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "test-admin")
                .put("action", "create")
                .putAll("role", "role1", "role2")
                .put("owner", "joe")
                .put("description", "desc")
                .build(), pw);
        String key = output.toString().split("\\n")[0].split(":")[1].trim();

        ApiKey apiKey = _authIdentityManager.getIdentity(key);
        assertNotNull(apiKey);
        assertEquals(apiKey.getId(), key);
        assertEquals(apiKey.getRoles(), ImmutableSet.of("role1", "role2"));
        assertEquals(apiKey.getOwner(), "joe");
        assertEquals(apiKey.getDescription(), "desc");
    }

    @Test
    public void testCreateNewApiKeyNoCreatePermission() throws Exception {
        createApiKeyWithPermissions("no-create-perm");

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "no-create-perm")
                .put("action", "create")
                .put("owner", "joe")
                .put("description", "desc")
                .build(), pw);

        assertEquals(output.toString(), "Not authorized\n");
        // No new identities except for the two generated by the unit test itself should exist.
        assertEquals(
                _authIdentityManager.getAllIdentities().stream().map(ApiKey::getId).collect(Collectors.toSet()),
                ImmutableSet.of("test-admin", "no-create-perm"));
    }

    @Test
    public void testCreateNewApiKeyInsufficientGrantPermission() throws Exception {
        createApiKeyWithPermissions("create-no-grant-perm",
                Permissions.createApiKey(),
                Permissions.grantRole(new NamedResource("group1")));

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "create-no-grant-perm")
                .put("action", "create")
                .putAll("role", "group1/allow", "deny")
                .put("owner", "joe")
                .put("description", "desc")
                .build(), pw);

        assertEquals(output.toString(), "Not authorized\n");
        // No new identities except for the two generated by the unit test itself should exist.
        assertEquals(
                _authIdentityManager.getAllIdentities().stream().map(ApiKey::getId).collect(Collectors.toSet()),
                ImmutableSet.of("test-admin", "create-no-grant-perm"));
    }

    @Test
    public void testUpdateApiKey() throws Exception {
        String key = "updateapikeytestkey";

        _authIdentityManager.updateIdentity(new ApiKey(key, "id_update", ImmutableSet.of("role1", "role2", "role3")));

        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "test-admin")
                .put("action", "update")
                .put("key", key)
                .putAll("addRole", "role4", "role5")
                .put("removeRole", "role3")
                .build(), mock(PrintWriter.class));

        ApiKey apiKey = _authIdentityManager.getIdentity(key);
        assertNotNull(apiKey);
        assertEquals(apiKey.getRoles(), ImmutableSet.of("role1", "role2", "role4", "role5"));
    }

    @Test
    public void testUpdateNewApiKeyInsufficientGrantPermissionOnAddedRole() throws Exception {
        createApiKeyWithPermissions("update-no-add-grant-perm",
                Permissions.grantRole(new NamedResource("group1")));

        String key = "updateapikeytestkey";
        _authIdentityManager.updateIdentity(new ApiKey(key, "id_update", ImmutableSet.of("role1", "role2", "role3")));

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "update-no-add-grant-perm")
                .put("action", "update")
                .put("key", key)
                .putAll("addRole", "group2/role4")
                .build(), pw);

        assertEquals(output.toString(), "Not authorized\n");
        // Roles should be unchanged
        assertEquals(_authIdentityManager.getIdentity(key).getRoles(), ImmutableSet.of("role1", "role2", "role3"));
    }

    @Test
    public void testUpdateNewApiKeyInsufficientGrantPermissionOnRemovedRole() throws Exception {
        createApiKeyWithPermissions("update-no-remove-grant-perm",
                Permissions.grantRole(new NamedResource("group1")));

        String key = "updateapikeytestkey";
        _authIdentityManager.updateIdentity(new ApiKey(key, "id_update", ImmutableSet.of("role1", "role2", "role3")));

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "update-no-remove-grant-perm")
                .put("action", "update")
                .put("key", key)
                .putAll("removeRole", "role1")
                .build(), pw);

        assertEquals(output.toString(), "Not authorized\n");
        // Roles should be unchanged
        assertEquals(_authIdentityManager.getIdentity(key).getRoles(), ImmutableSet.of("role1", "role2", "role3"));
    }

    @Test
    public void testMigrateApiKey() throws Exception {
        String key = "migrateapikeytestkey";

        _authIdentityManager.updateIdentity(new ApiKey(key, "id_migrate", ImmutableSet.of("role1", "role2")));
        assertNotNull(_authIdentityManager.getIdentity(key));

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.of(
                ApiKeyRequest.AUTHENTICATION_PARAM, "test-admin",
                "action", "migrate", "key", key), pw);
        String newKey = output.toString().split("\\n")[0].split(":")[1].trim();

        ApiKey apiKey = _authIdentityManager.getIdentity(newKey);
        assertNotNull(apiKey);
        assertEquals(apiKey.getRoles(), ImmutableSet.of("role1", "role2"));
        assertEquals(apiKey.getInternalId(), "id_migrate");
        assertNull(_authIdentityManager.getIdentity(key));
    }

    @Test
    public void testMigrateNewApiKeyNoUpdatePermission() throws Exception {
        createApiKeyWithPermissions("no-update-perm");

        String key = "migrateapikeytestkey";
        _authIdentityManager.updateIdentity(new ApiKey(key, "id_migrate", ImmutableSet.of("role1", "role2")));
        assertNotNull(_authIdentityManager.getIdentity(key));

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.of(
                ApiKeyRequest.AUTHENTICATION_PARAM, "no-update-perm",
                "action", "migrate", "key", key), pw);

        assertEquals(output.toString(), "Not authorized\n");
        // API key should be unchanged
        assertNotNull(_authIdentityManager.getIdentity(key));
    }

    @Test
    public void testDeleteApiKey() throws Exception {
        String key = "deleteapikeytestkey";

        _authIdentityManager.updateIdentity(new ApiKey(key, "id_delete", ImmutableSet.of("role1", "role2")));
        assertNotNull(_authIdentityManager.getIdentity(key));

        _task.execute(ImmutableMultimap.of(
                ApiKeyRequest.AUTHENTICATION_PARAM, "test-admin",
                "action", "delete", "key", key), mock(PrintWriter.class));
        assertNull(_authIdentityManager.getIdentity(key));
    }

    @Test
    public void testDeleteApiKeyNoDeletePermission() throws Exception {
        createApiKeyWithPermissions("no-delete-perm");

        String key = "deleteapikeytestkey";
        _authIdentityManager.updateIdentity(new ApiKey(key, "id_delete", ImmutableSet.of("role1", "role2")));
        assertNotNull(_authIdentityManager.getIdentity(key));

        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.of(
                ApiKeyRequest.AUTHENTICATION_PARAM, "no-delete-perm",
                "action", "delete", "key", key), pw);

        assertEquals(output.toString(), "Not authorized\n");
        assertNotNull(_authIdentityManager.getIdentity(key));
    }

    @Test (expectedExceptions = IllegalArgumentException.class)
    public void testCreateApiKeyWithReservedRole() throws Exception {
        StringWriter output = new StringWriter();
        PrintWriter pw = new PrintWriter(output);
        _task.execute(ImmutableMultimap.<String, String>builder()
                .put(ApiKeyRequest.AUTHENTICATION_PARAM, "test-admin")
                .put("action", "create")
                .putAll("role", "role1", "reservedrole")
                .put("owner", "joe")
                .put("description", "desc")
                .build(), pw);
    }
}
