cluster_name: 'local_default'
hinted_handoff_enabled: false
max_hint_window_in_ms: 3600000
hinted_handoff_throttle_in_kb: 1024
batchlog_replay_throttle_in_kb: 1024
max_hints_delivery_threads: 2
authenticator: org.apache.cassandra.auth.AllowAllAuthenticator
authorizer: org.apache.cassandra.auth.AllowAllAuthorizer
permissions_validity_in_ms: 2000
partitioner: org.apache.cassandra.dht.ByteOrderedPartitioner
data_file_directories:
  - /var/lib/cassandra/data
commitlog_directory: /var/lib/cassandra/commitlog
disk_failure_policy: stop
commit_failure_policy: stop
key_cache_size_in_mb: null
key_cache_save_period: 14400
row_cache_size_in_mb: 0
row_cache_save_period: 0
saved_caches_directory: /var/lib/cassandra/saved_caches
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
      - seeds:  "cassandra-dc1"
endpoint_snitch: GossipingPropertyFileSnitch
concurrent_reads: 32
concurrent_writes: 64
#memtable_flush_queue_size: 4
trickle_fsync: false
trickle_fsync_interval_in_kb: 10240
storage_port: 7000
listen_address: 0.0.0.0 #127.0.0.1
start_native_transport: true
native_transport_port: 9042
start_rpc: true
rpc_address: 0.0.0.0 # 127.0.0.1
rpc_port: 9160
rpc_keepalive: true
rpc_server_type: sync
broadcast_rpc_address: 127.0.0.1
thrift_framed_transport_size_in_mb: 15
incremental_backups: false
snapshot_before_compaction: false
auto_snapshot: false
column_index_size_in_kb: 64
compaction_throughput_mb_per_sec: 128
read_request_timeout_in_ms: 10000
range_request_timeout_in_ms: 10000
write_request_timeout_in_ms: 10000
truncate_request_timeout_in_ms: 60000
request_timeout_in_ms: 10000
cross_node_timeout: false
dynamic_snitch_update_interval_in_ms: 100
dynamic_snitch_reset_interval_in_ms: 600000
dynamic_snitch_badness_threshold: 0.1
request_scheduler: org.apache.cassandra.scheduler.NoScheduler
inter_dc_tcp_nodelay: true
rpc_min_threads: 16
rpc_max_threads: 2048
stream_throughput_outbound_megabits_per_sec: '400'
dynamic_snitch: true
concurrent_compactors: 1
num_tokens: 1
auto_bootstrap: true
cas_contention_timeout_in_ms: 1000
file_cache_size_in_mb: '512'
